supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc

onlyBuiltDependencies:
  - aws-sdk
  - esbuild
  - sharp
  - unrs-resolver

patchedDependencies:
  masonic@4.1.0: patches/masonic@4.1.0.patch
