#!/bin/sh

INIT_IMAGE="overture-creations-5sI6fQgYIuo.png"
MASK_IMAGE="overture-creations-5sI6fQgYIuo_mask.png"

mkdir tmp
base64 $INIT_IMAGE > tmp/init_image
base64 $MASK_IMAGE > tmp/mask_image

jq \
  --null-input \
  --compact-output \
  --arg prompt "A cat sits on a bench" \
  --rawfile init_image tmp/init_image \
  --rawfile mask_image tmp/mask_image \
  '{"prompt": $prompt, "init_image", $init_image, "mask_image": $mask_image}' \
| curl \
  -X POST \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
  -d @- \
  http://localhost:8000/


